"""empty message

Revision ID: 506e478e0611
Revises: 5b1f1d56cb45
Create Date: 2019-06-03 19:04:16.345696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506e478e0611'
down_revision = '5b1f1d56cb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_user_id_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('post_user_id_fkey', 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
